# Generated by Django 3.2 on 2021-04-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('Tw', 'Topwear'), ('Bw', 'Bootomwear')], max_length=2),
        ),
    ]
